# Form implementation generated from reading ui file 'C:/Users/a21alejandrovg/PycharmProjects/vazquezgonzalez/views/dialDatos.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgDatos(object):
    def setupUi(self, dlgDatos):
        dlgDatos.setObjectName("dlgDatos")
        dlgDatos.resize(400, 300)
        self.chbCliente = QtWidgets.QCheckBox(dlgDatos)
        self.chbCliente.setGeometry(QtCore.QRect(60, 130, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chbCliente.setFont(font)
        self.chbCliente.setObjectName("chbCliente")
        self.buttonGroup = QtWidgets.QButtonGroup(dlgDatos)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.setExclusive(False)
        self.buttonGroup.addButton(self.chbCliente)
        self.chbCoche = QtWidgets.QCheckBox(dlgDatos)
        self.chbCoche.setGeometry(QtCore.QRect(60, 170, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chbCoche.setFont(font)
        self.chbCoche.setObjectName("chbCoche")
        self.buttonGroup.addButton(self.chbCoche)
        self.label = QtWidgets.QLabel(dlgDatos)
        self.label.setGeometry(QtCore.QRect(130, 50, 141, 16))
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dlgDatos)
        self.label_2.setGeometry(QtCore.QRect(210, 90, 150, 150))
        self.label_2.setMinimumSize(QtCore.QSize(150, 150))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/a21alejandrovg/PycharmProjects/vazquezgonzalez/views\\../img/pregunta_exportacion.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.btnAceptar = QtWidgets.QPushButton(dlgDatos)
        self.btnAceptar.setGeometry(QtCore.QRect(170, 260, 75, 23))
        self.btnAceptar.setObjectName("btnAceptar")

        self.retranslateUi(dlgDatos)
        QtCore.QMetaObject.connectSlotsByName(dlgDatos)

    def retranslateUi(self, dlgDatos):
        _translate = QtCore.QCoreApplication.translate
        dlgDatos.setWindowTitle(_translate("dlgDatos", "Dialog"))
        self.chbCliente.setText(_translate("dlgDatos", "Cliente"))
        self.chbCoche.setText(_translate("dlgDatos", "Coche"))
        self.label.setText(_translate("dlgDatos", "Elija el tipo de dato"))
        self.btnAceptar.setText(_translate("dlgDatos", "Aceptar"))
