# Form implementation generated from reading ui file 'C:/Users/a21alejandrovg/PycharmProjects/vazquezgonzalez/views/dlgCalendar.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgCalendar(object):
    def setupUi(self, dlgCalendar):
        dlgCalendar.setObjectName("dlgCalendar")
        dlgCalendar.resize(400, 300)
        self.calendario = QtWidgets.QCalendarWidget(dlgCalendar)
        self.calendario.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.calendario.setObjectName("calendario")

        self.retranslateUi(dlgCalendar)
        QtCore.QMetaObject.connectSlotsByName(dlgCalendar)

    def retranslateUi(self, dlgCalendar):
        _translate = QtCore.QCoreApplication.translate
        dlgCalendar.setWindowTitle(_translate("dlgCalendar", "Dialog"))
